"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Copy, MapPin, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { DataTable, type LedgerColumn } from "@/components/transactions/data-table";
import { DeleteDialog } from "@/components/transactions/delete-dialog";
import { FilterBar, FilterField, type ActiveFilter } from "@/components/transactions/filter-bar";
import { RecordSheet } from "@/components/transactions/record-sheet";
import { TransactionPage, TransactionPageHeader } from "@/components/transactions/transaction-page";
import styles from "@/components/transactions/transaction-ledger.module.css";
import type { Client, MileageEntry, MileageRecentTrip, Project } from "@/lib/types";

type Direction = "asc" | "desc";
type MileageSort = "date" | "tripName" | "startAddress" | "endAddress" | "purpose" | "miles" | "roundTrip" | "totalMiles" | "billable" | "reimbursement" | "createdAt" | "updatedAt";
type MileageFilters = {
  page: number; pageSize: number; sort: MileageSort; direction: Direction; search: string; from: string; to: string;
  clientId: string; projectId: string; roundTrip: string; billable: string; id: string; mcId: string;
  tripName: string; startAddress: string; endAddress: string; purpose: string; notes: string;
  milesMin: string; milesMax: string; totalMilesMin: string; totalMilesMax: string;
  reimbursementMin: string; reimbursementMax: string; createdFrom: string; createdTo: string; updatedFrom: string; updatedTo: string;
};
type PageInfo = { page: number; pageSize: number; totalItems: number; totalPages: number; hasPreviousPage: boolean; hasNextPage: boolean };
type Totals = { entries: number; totalMiles: number; reimbursement: number };
type Facets = { purposes: Array<{ value: string; count: number }> };
type Place = { id: string; label: string; longitude: number; latitude: number };
type RouteAlternative = { id: string; label: string; miles: number; durationMinutes: number; metadata: Record<string, unknown> };
type RouteResult = { provider: string; start: Place; end: Place; routes: RouteAlternative[]; calculatedAt: string; cached: boolean };
type FormValues = { date: string; tripName: string; startAddress: string; endAddress: string; miles: string; roundTrip: boolean; purpose: string; clientId: string; projectId: string; billable: boolean; notes: string; calculationSource: "manual" | "provider"; calculationProvider: string | null; calculatedMiles: number | null; routeMetadataJson: string | null; calculatedAt: string | null; startPlaceId: string | null; endPlaceId: string | null };

const DEFAULT_FILTERS: MileageFilters = { page: 1, pageSize: 50, sort: "date", direction: "desc", search: "", from: "", to: "", clientId: "", projectId: "", roundTrip: "", billable: "", id: "", mcId: "", tripName: "", startAddress: "", endAddress: "", purpose: "", notes: "", milesMin: "", milesMax: "", totalMilesMin: "", totalMilesMax: "", reimbursementMin: "", reimbursementMax: "", createdFrom: "", createdTo: "", updatedFrom: "", updatedTo: "" };
const FILTER_KEYS = Object.keys(DEFAULT_FILTERS) as Array<keyof MileageFilters>;
const EMPTY_PAGE: PageInfo = { page: 1, pageSize: 50, totalItems: 0, totalPages: 0, hasPreviousPage: false, hasNextPage: false };
const EMPTY_TOTALS: Totals = { entries: 0, totalMiles: 0, reimbursement: 0 };

function redirectedToLogin(response: Response): boolean { if (response.status !== 401) return false;
  // eslint-disable-next-line @next/next/no-location-assign-relative-destination
  window.location.assign(`/login?next=${encodeURIComponent(window.location.pathname + window.location.search)}`); return true; }
function todayKey(): string { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`; }
function money(value: number): string { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value); }
function friendlyDate(value: string): string { const date = new Date(`${value}T12:00:00`); return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(date) : value; }
function blankForm(): FormValues { return { date: todayKey(), tripName: "", startAddress: "", endAddress: "", miles: "", roundTrip: false, purpose: "", clientId: "", projectId: "", billable: false, notes: "", calculationSource: "manual", calculationProvider: null, calculatedMiles: null, routeMetadataJson: null, calculatedAt: null, startPlaceId: null, endPlaceId: null }; }
function entryForm(entry: MileageEntry, duplicate = false): FormValues { return { date: duplicate ? todayKey() : entry.date, tripName: entry.tripName, startAddress: entry.startAddress, endAddress: entry.endAddress, miles: String(entry.miles), roundTrip: entry.roundTrip, purpose: entry.purpose, clientId: entry.clientId || "", projectId: entry.projectId || "", billable: entry.billable, notes: entry.notes, calculationSource: entry.calculationSource, calculationProvider: entry.calculationProvider, calculatedMiles: entry.calculatedMiles, routeMetadataJson: entry.routeMetadataJson, calculatedAt: entry.calculatedAt, startPlaceId: entry.startPlaceId, endPlaceId: entry.endPlaceId }; }
function recentForm(recent: MileageRecentTrip): FormValues { return { ...blankForm(), tripName: recent.tripName, startAddress: recent.startAddress, endAddress: recent.endAddress, miles: String(recent.miles), roundTrip: recent.roundTrip, purpose: recent.purpose }; }
function payload(values: FormValues) { return { ...values, miles: Number(values.miles), clientId: values.clientId || null, projectId: values.projectId || null }; }
function useDebouncedValue(value: string, delay: number): string { const [debounced, setDebounced] = useState(value); useEffect(() => { const timer = window.setTimeout(() => setDebounced(value), delay); return () => window.clearTimeout(timer); }, [value, delay]); return debounced; }
function filtersFromUrl(): MileageFilters { const params = new URLSearchParams(window.location.search); const result = { ...DEFAULT_FILTERS }; for (const key of FILTER_KEYS) { const value = params.get(key); if (value === null) continue; if (key === "page" || key === "pageSize") { const parsed = Number(value); if (Number.isInteger(parsed) && parsed > 0) result[key] = parsed; } else (result[key] as string) = value; } const saved = Number(window.localStorage.getItem("transaction-ledger.mileage.page-size")); if (!params.has("pageSize") && [25, 50, 100].includes(saved)) result.pageSize = saved; return result; }
function queryString(filters: MileageFilters): string { const params = new URLSearchParams(); for (const key of FILTER_KEYS) { const value = filters[key]; if (value === "" || value === DEFAULT_FILTERS[key]) continue; params.set(key, String(value)); } params.set("page", String(filters.page)); params.set("pageSize", String(filters.pageSize)); params.set("sort", filters.sort); params.set("direction", filters.direction); return params.toString(); }

/** Shortest address worth sending to the geocoder; below this it is a fragment. */
const MIN_ADDRESS_LENGTH = 5;
function routeKey(start: string, end: string): string { return `${start.trim().toLowerCase()}|${end.trim().toLowerCase()}`; }
function routeFields(result: RouteResult, route: RouteAlternative): Partial<FormValues> {
  return { miles: String(route.miles), calculationSource: "provider", calculationProvider: result.provider, calculatedMiles: route.miles, routeMetadataJson: JSON.stringify(route.metadata), calculatedAt: result.calculatedAt, startPlaceId: result.start.id, endPlaceId: result.end.id };
}

function AddressField({ label, value, configured, onChange, onSelect }: { label: string; value: string; configured: boolean; onChange: (value: string) => void; onSelect: (place: Place) => void }) {
  const [suggestions, setSuggestions] = useState<Place[]>([]); const [busy, setBusy] = useState(false); const [typed, setTyped] = useState(""); const query = useDebouncedValue(typed, 350).trim();
  // Suggestions follow what was typed, not the field's value: the form rewrites
  // the address to the provider's normalized label after a route is
  // calculated, and that must not reopen the dropdown over a settled field.
  const editing = typed.trim() === value.trim();
  useEffect(() => { if (!configured || query.length < 3 || query !== value.trim()) return; const controller = new AbortController(); const timer = window.setTimeout(() => { setBusy(true); void fetch(`/api/maps/autocomplete?q=${encodeURIComponent(query)}`, { signal: controller.signal }).then(async (response) => { const json = await response.json().catch(() => ({})); if (response.ok) setSuggestions(Array.isArray(json.suggestions) ? json.suggestions : []); }).catch(() => {}).finally(() => setBusy(false)); }, 0); return () => { window.clearTimeout(timer); controller.abort(); }; }, [configured, query, value]);
  return <div className={`${styles.sheetField} ${styles.spanAll} ${styles.addressField}`}><label><span className={styles.fieldLabel}>{label}</span><input className={styles.input} autoComplete="street-address" value={value} placeholder={label === "From" ? "Starting address" : "Destination address"} onChange={(event) => { setTyped(event.target.value); onChange(event.target.value); setSuggestions([]); }} /></label>{busy && editing ? <span className={styles.addressHint}>Searching addresses…</span> : null}{editing && suggestions.length ? <div className={styles.addressSuggestions}>{suggestions.map((place) => <button key={place.id} type="button" onClick={() => { setTyped(place.label); onSelect(place); setSuggestions([]); }}>{place.label}</button>)}</div> : null}</div>;
}

function MileageForm({ formId, initial, clients, projects, recent, rate, mapsConfigured, onDirtyChange, onSubmit }: { formId: string; initial: FormValues; clients: Client[]; projects: Project[]; recent: MileageRecentTrip[]; rate: number; mapsConfigured: boolean; onDirtyChange: (dirty: boolean) => void; onSubmit: (values: FormValues, addAnother: boolean) => void }) {
  const [values, setValues] = useState(initial); const dirty = JSON.stringify(values) !== JSON.stringify(initial);
  const [startPlace, setStartPlace] = useState<Place | null>(null); const [endPlace, setEndPlace] = useState<Place | null>(null); const [routeResult, setRouteResult] = useState<RouteResult | null>(null); const [routeBusy, setRouteBusy] = useState(false); const [routeError, setRouteError] = useState("");
  // Every address pair is calculated at most once, and the pair the form opened
  // on counts as already calculated: saved and duplicated trips keep the miles
  // they were saved with instead of being silently restated on open.
  const calculated = useRef(new Set([routeKey(initial.startAddress, initial.endAddress)])); const requestSeq = useRef(0);
  useEffect(() => onDirtyChange(dirty), [dirty, onDirtyChange]);
  const selectableProjects = projects.filter((project) => !values.clientId || project.clientId === values.clientId || project.id === values.projectId);
  const totalMiles = (Number(values.miles) || 0) * (values.roundTrip ? 2 : 1); const reimbursement = totalMiles * rate;
  const debouncedStart = useDebouncedValue(values.startAddress, 700); const debouncedEnd = useDebouncedValue(values.endAddress, 700);
  const calculateRoute = useCallback(async (start: string | Place, end: string | Place) => {
    const seq = (requestSeq.current += 1); setRouteBusy(true); setRouteError("");
    try {
      const response = await fetch("/api/maps/distance", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ start, end }) });
      const json = await response.json().catch(() => ({}));
      if (seq !== requestSeq.current) return;
      if (!response.ok) throw new Error(typeof json.error === "string" ? json.error : "Unable to calculate route.");
      const result = json as RouteResult; const route = result.routes[0];
      if (!route) throw new Error("No driving route was returned. Enter miles manually.");
      setRouteResult(result); calculated.current.add(routeKey(result.start.label, result.end.label));
      setValues((current) => ({ ...current, startAddress: result.start.label, endAddress: result.end.label, ...routeFields(result, route) }));
    } catch (caught) {
      if (seq === requestSeq.current) setRouteError(caught instanceof Error ? caught.message : String(caught));
    } finally { if (seq === requestSeq.current) setRouteBusy(false); }
  }, []);
  // Both addresses present is the whole trigger — typing them is as valid as
  // picking them from the suggestion list, and a trip is not entered twice.
  useEffect(() => {
    if (!mapsConfigured) return;
    const start = debouncedStart.trim(); const end = debouncedEnd.trim();
    if (start.length < MIN_ADDRESS_LENGTH || end.length < MIN_ADDRESS_LENGTH) return;
    const key = routeKey(start, end);
    if (calculated.current.has(key)) return;
    calculated.current.add(key);
    void calculateRoute(startPlace?.label.trim() === start ? startPlace : start, endPlace?.label.trim() === end ? endPlace : end);
  }, [mapsConfigured, debouncedStart, debouncedEnd, startPlace, endPlace, calculateRoute]);
  function selectRoute(route: RouteAlternative) { if (!routeResult) return; setValues((current) => ({ ...current, ...routeFields(routeResult, route) })); }
  return <form id={formId} className={styles.sheetForm} onSubmit={(event) => { event.preventDefault(); const submitter = (event.nativeEvent as SubmitEvent).submitter as HTMLButtonElement | null; onSubmit(values, submitter?.value === "another"); }}>
    {recent.length > 0 ? <div className={styles.recentRouteSection}><span className={styles.fieldLabel}>Recent routes</span><div className={styles.recentRouteList}>{recent.slice(0, 4).map((route, index) => <button key={`${route.startAddress}-${route.endAddress}-${index}`} type="button" className={styles.recentRouteButton} onClick={() => { calculated.current.add(routeKey(route.startAddress, route.endAddress)); setRouteError(""); setValues((current) => ({ ...current, ...recentForm(route), date: current.date, clientId: current.clientId, projectId: current.projectId, billable: current.billable })); }}><strong>{route.tripName || `${route.startAddress} → ${route.endAddress}`}</strong><span>{route.miles.toFixed(1)} mi{route.roundTrip ? " each way · round trip" : " one way"}</span></button>)}</div></div> : null}
    <label className={styles.sheetField}><span className={styles.fieldLabel}>Date</span><input className={styles.input} type="date" value={values.date} required onChange={(event) => setValues((current) => ({ ...current, date: event.target.value }))} /></label>
    <label className={styles.sheetField}><span className={styles.fieldLabel}>Trip name</span><input className={styles.input} value={values.tripName} placeholder="Office to client" autoFocus onChange={(event) => setValues((current) => ({ ...current, tripName: event.target.value }))} /></label>
    <AddressField label="From" value={values.startAddress} configured={mapsConfigured} onChange={(value) => { setStartPlace(null); setRouteResult(null); setValues((current) => ({ ...current, startAddress: value, calculationSource: "manual", calculationProvider: null, calculatedMiles: null, routeMetadataJson: null, calculatedAt: null, startPlaceId: null })); }} onSelect={(place) => { setStartPlace(place); setValues((current) => ({ ...current, startAddress: place.label, startPlaceId: place.id })); }} />
    <AddressField label="To" value={values.endAddress} configured={mapsConfigured} onChange={(value) => { setEndPlace(null); setRouteResult(null); setValues((current) => ({ ...current, endAddress: value, calculationSource: "manual", calculationProvider: null, calculatedMiles: null, routeMetadataJson: null, calculatedAt: null, endPlaceId: null })); }} onSelect={(place) => { setEndPlace(place); setValues((current) => ({ ...current, endAddress: place.label, endPlaceId: place.id })); }} />
    <label className={styles.sheetField}><span className={styles.fieldLabel}>One-way miles</span><input className={styles.input} type="number" inputMode="decimal" min="0.01" max="10000" step="0.01" value={values.miles} required onChange={(event) => setValues((current) => ({ ...current, miles: event.target.value, calculationSource: "manual", calculationProvider: null, calculatedMiles: null, routeMetadataJson: null, calculatedAt: null }))} /><span className={styles.addressHint}>{routeBusy ? "Calculating driving distance…" : values.calculationSource === "provider" ? `Calculated by ${values.calculationProvider}` : "Manual mileage"}</span></label>
    <label className={styles.toggleField}><span>Round trip</span><input type="checkbox" checked={values.roundTrip} onChange={(event) => setValues((current) => ({ ...current, roundTrip: event.target.checked }))} /></label>
    <div className={styles.routeControls}><button type="button" className={styles.secondaryButton} disabled={!mapsConfigured || routeBusy || values.startAddress.trim().length < MIN_ADDRESS_LENGTH || values.endAddress.trim().length < MIN_ADDRESS_LENGTH} onClick={() => void calculateRoute(startPlace?.label.trim() === values.startAddress.trim() ? startPlace : values.startAddress.trim(), endPlace?.label.trim() === values.endAddress.trim() ? endPlace : values.endAddress.trim())}>{routeBusy ? "Calculating…" : routeResult ? "Recalculate driving route" : "Calculate driving route"}</button>{!mapsConfigured ? <span>Configure Maps in Settings, or enter miles manually.</span> : <span>Miles update automatically once both addresses are entered.</span>}{routeError ? <span className={styles.routeError}>{routeError} Enter miles manually to save this trip.</span> : null}</div>
    {routeResult && routeResult.routes.length > 1 ? <label className={`${styles.sheetField} ${styles.spanAll}`}><span className={styles.fieldLabel}>Route</span><select className={styles.select} value={String(values.calculatedMiles ?? "")} onChange={(event) => { const route = routeResult.routes.find((candidate) => String(candidate.miles) === event.target.value); if (route) selectRoute(route); }}>{routeResult.routes.map((route) => <option key={route.id} value={String(route.miles)}>{route.label} · {route.miles.toFixed(2)} mi · {route.durationMinutes} min</option>)}</select></label> : null}
    <label className={`${styles.sheetField} ${styles.spanAll}`}><span className={styles.fieldLabel}>Purpose</span><input className={styles.input} value={values.purpose} placeholder="Client meeting" onChange={(event) => setValues((current) => ({ ...current, purpose: event.target.value }))} /></label>
    <div className={styles.calculation} aria-label="Mileage reimbursement calculation"><div><strong>{totalMiles.toFixed(2)} mi</strong><span>{values.roundTrip ? "Round-trip total" : "One-way total"}</span></div><div><strong>Estimated {money(reimbursement)}</strong><span>{totalMiles.toFixed(2)} mi × {money(rate)}</span></div></div>
    <p className={styles.sheetSectionLabel}>Assignment</p>
    <label className={styles.sheetField}><span className={styles.fieldLabel}>Client</span><select className={styles.select} value={values.clientId} onChange={(event) => { const clientId = event.target.value; setValues((current) => ({ ...current, clientId, projectId: projects.some((project) => project.id === current.projectId && project.clientId === clientId) ? current.projectId : "" })); }}><option value="">Unassigned</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}{client.isArchived ? " (archived)" : ""}</option>)}</select></label>
    <label className={styles.sheetField}><span className={styles.fieldLabel}>Project</span><select className={styles.select} value={values.projectId} onChange={(event) => { const project = projects.find((candidate) => candidate.id === event.target.value); setValues((current) => ({ ...current, projectId: event.target.value, clientId: project?.clientId ?? current.clientId })); }}><option value="">No project</option>{selectableProjects.map((project) => <option key={project.id} value={project.id}>{project.name}{project.isArchived ? " (archived)" : ""}</option>)}</select></label>
    <label className={`${styles.toggleField} ${styles.spanAll}`}><span>Billable</span><input type="checkbox" checked={values.billable} onChange={(event) => setValues((current) => ({ ...current, billable: event.target.checked }))} /></label>
    <details className={styles.detailsDisclosure}><summary>More details</summary><div className={styles.detailsGrid}><label className={`${styles.sheetField} ${styles.spanAll}`}><span className={styles.fieldLabel}>Notes</span><textarea className={styles.textarea} value={values.notes} onChange={(event) => setValues((current) => ({ ...current, notes: event.target.value }))} /></label></div></details>
  </form>;
}

export default function MileagePage() {
  const [ready, setReady] = useState(false); const [filters, setFilters] = useState(DEFAULT_FILTERS); const [advancedOpen, setAdvancedOpen] = useState(false);
  const [entries, setEntries] = useState<MileageEntry[]>([]); const [pageInfo, setPageInfo] = useState<PageInfo>(EMPTY_PAGE); const [totals, setTotals] = useState<Totals>(EMPTY_TOTALS); const [facets, setFacets] = useState<Facets>({ purposes: [] });
  const [clients, setClients] = useState<Client[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [recent, setRecent] = useState<MileageRecentTrip[]>([]); const [rate, setRate] = useState(0.67); const [mapsConfigured, setMapsConfigured] = useState(false);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [sheetMode, setSheetMode] = useState<"create" | "edit" | null>(null); const [editingEntry, setEditingEntry] = useState<MileageEntry | null>(null); const [formSeed, setFormSeed] = useState<FormValues | null>(null); const [formKey, setFormKey] = useState(0); const [formDirty, setFormDirty] = useState(false); const [deleteEntry, setDeleteEntry] = useState<MileageEntry | null>(null);
  const debouncedSearch = useDebouncedValue(filters.search, 300); const debouncedTripName = useDebouncedValue(filters.tripName, 300); const debouncedStart = useDebouncedValue(filters.startAddress, 300); const debouncedEnd = useDebouncedValue(filters.endAddress, 300); const debouncedPurpose = useDebouncedValue(filters.purpose, 300); const debouncedNotes = useDebouncedValue(filters.notes, 300);
  const requestQuery = queryString({ ...filters, search: debouncedSearch, tripName: debouncedTripName, startAddress: debouncedStart, endAddress: debouncedEnd, purpose: debouncedPurpose, notes: debouncedNotes });
  const patchFilters = useCallback((patch: Partial<MileageFilters>, keepPage = false) => setFilters((current) => ({ ...current, ...patch, page: keepPage && patch.page !== undefined ? patch.page : 1 })), []);

  useEffect(() => { const timer = window.setTimeout(() => { setFilters(filtersFromUrl()); setReady(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (!ready) return; window.history.replaceState(null, "", `${window.location.pathname}?${queryString(filters)}`); window.localStorage.setItem("transaction-ledger.mileage.page-size", String(filters.pageSize)); }, [filters, ready]);
  useEffect(() => { void (async () => { try { const [clientResponse, projectResponse] = await Promise.all([fetch("/api/clients?includeArchived=1", { cache: "no-store" }), fetch("/api/projects?includeArchived=1", { cache: "no-store" })]); if (redirectedToLogin(clientResponse) || redirectedToLogin(projectResponse)) return; const [clientJson, projectJson] = await Promise.all([clientResponse.json(), projectResponse.json()]); if (!clientResponse.ok || !projectResponse.ok) throw new Error("Client/project fetch failed"); setClients(Array.isArray(clientJson?.clients) ? clientJson.clients : []); setProjects(Array.isArray(projectJson?.projects) ? projectJson.projects : []); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } })(); }, []);
  const loadEntries = useCallback(async (signal?: AbortSignal) => { if (!ready) return; setLoading(true); setError(null); try { const response = await fetch(`/api/mileage?${requestQuery}`, { cache: "no-store", signal }); if (redirectedToLogin(response)) return; const json = await response.json(); if (!response.ok) throw new Error(json?.error || "Mileage fetch failed"); setEntries(Array.isArray(json?.items) ? json.items : []); setPageInfo(json?.pageInfo ?? EMPTY_PAGE); setTotals(json?.filteredTotals ?? EMPTY_TOTALS); setFacets(json?.availableFacets ?? { purposes: [] }); setRecent(Array.isArray(json?.recentTrips) ? json.recentTrips : []); setRate(Number(json?.mileageRate ?? 0.67)); setMapsConfigured(Boolean(json?.maps?.configured)); } catch (caught) { if (caught instanceof DOMException && caught.name === "AbortError") return; setError(caught instanceof Error ? caught.message : String(caught)); } finally { setLoading(false); } }, [ready, requestQuery]);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => void loadEntries(controller.signal), 0); return () => { window.clearTimeout(timer); controller.abort(); }; }, [loadEntries]);
  async function mutate(method: string, path: string, body?: unknown): Promise<boolean> { setBusy(true); setError(null); try { const response = await fetch(path, { method, headers: body === undefined ? undefined : { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) }); if (redirectedToLogin(response)) return false; const json = await response.json().catch(() => null); if (!response.ok) throw new Error(json?.error || `${method} failed`); await loadEntries(); return true; } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); return false; } finally { setBusy(false); } }
  function openCreate(seed?: FormValues) { setEditingEntry(null); setFormSeed(seed ?? blankForm()); setFormKey((current) => current + 1); setFormDirty(false); setSheetMode("create"); }
  function openEdit(entry: MileageEntry) { setEditingEntry(entry); setFormSeed(entryForm(entry)); setFormKey((current) => current + 1); setFormDirty(false); setSheetMode("edit"); }

  const clientNames = useMemo(() => new Map(clients.map((client) => [client.id, client.name])), [clients]); const projectNames = useMemo(() => new Map(projects.map((project) => [project.id, project.name])), [projects]); const activeProjects = useMemo(() => projects.filter((project) => !filters.clientId || project.clientId === filters.clientId), [projects, filters.clientId]);
  const activeFilters = useMemo(() => { const values: ActiveFilter[] = []; const add = (key: keyof MileageFilters, label: string) => { if (!filters[key] || key === "page" || key === "pageSize" || key === "sort" || key === "direction") return; values.push({ id: key, label, onRemove: () => patchFilters({ [key]: "" } as Partial<MileageFilters>) }); }; add("search", `Search: ${filters.search}`); add("from", `From: ${filters.from}`); add("to", `To: ${filters.to}`); add("clientId", `Client: ${clientNames.get(filters.clientId) || filters.clientId}`); add("projectId", `Project: ${projectNames.get(filters.projectId) || filters.projectId}`); add("roundTrip", filters.roundTrip === "true" ? "Round trip" : "One way"); add("billable", filters.billable === "true" ? "Billable" : "Not billable"); for (const key of ["id", "mcId", "tripName", "startAddress", "endAddress", "purpose", "notes", "milesMin", "milesMax", "totalMilesMin", "totalMilesMax", "reimbursementMin", "reimbursementMax", "createdFrom", "createdTo", "updatedFrom", "updatedTo"] as const) add(key, `${key}: ${filters[key]}`); return values; }, [filters, clientNames, projectNames, patchFilters]);
  const columns: LedgerColumn<MileageEntry, MileageSort>[] = [
    { id: "date", label: "Date", sort: "date", render: (entry) => friendlyDate(entry.date) },
    { id: "tripName", label: "Trip", sort: "tripName", render: (entry) => <div><strong>{entry.tripName || entry.purpose || "Untitled trip"}</strong>{entry.purpose && entry.tripName ? <span className={styles.secondaryText}>{entry.purpose}</span> : null}</div> },
    { id: "route", label: "Route", render: (entry) => <div className={styles.routeCell}><span>{entry.startAddress || "Start"}</span><span>→ {entry.endAddress || "Destination"}</span></div> },
    { id: "assignment", label: "Client / project", render: (entry) => projectNames.get(entry.projectId || "") || clientNames.get(entry.clientId || "") || <span className={styles.secondaryText}>Unassigned</span> },
    { id: "totalMiles", label: "Total miles", sort: "totalMiles", render: (entry) => <strong>{entry.totalMiles.toFixed(2)}</strong> },
    { id: "reimbursement", label: "Reimbursement", sort: "reimbursement", render: (entry) => money(entry.totalMiles * rate) },
    { id: "billable", label: "Billable", sort: "billable", render: (entry) => <span className={`${styles.status} ${entry.billable ? styles.statusActive : ""}`}>{entry.billable ? "Billable" : "Business"}</span> },
    { id: "actions", label: "Actions", render: (entry) => <div className={styles.rowActions}><button type="button" className={styles.iconButton} onClick={() => openEdit(entry)} aria-label={`Edit ${friendlyDate(entry.date)} trip`}><Pencil size={15} /></button><button type="button" className={styles.iconButton} onClick={() => openCreate(entryForm(entry, true))} aria-label={`Duplicate ${friendlyDate(entry.date)} trip`}><Copy size={15} /></button><button type="button" className={styles.iconButton} onClick={() => setDeleteEntry(entry)} aria-label={`Delete ${friendlyDate(entry.date)} trip`}><Trash2 size={15} /></button></div> }
  ];
  const formId = `mileage-form-${formKey}`; const hasAnyRecords = pageInfo.totalItems > 0 || activeFilters.length === 0;
  return <TransactionPage>
    <TransactionPageHeader title="Mileage" metrics={[{ label: "filtered miles", value: totals.totalMiles.toFixed(1) }, { label: "reimbursement", value: money(totals.reimbursement) }]} action={<button type="button" className={styles.primaryButton} onClick={() => openCreate()}><Plus size={16} /> Log trip</button>} />
    {error ? <div className={styles.errorBanner}><span>{error}</span><button type="button" className={styles.quietButton} onClick={() => void loadEntries()}>Retry</button></div> : null}
    <FilterBar advancedOpen={advancedOpen} onToggleAdvanced={() => setAdvancedOpen((current) => !current)} activeFilters={activeFilters} onClear={() => setFilters((current) => ({ ...DEFAULT_FILTERS, pageSize: current.pageSize }))} advanced={<>
      <div className={styles.filterMobileOnly}><FilterField label="Trip type"><select className={styles.select} value={filters.roundTrip} onChange={(event) => patchFilters({ roundTrip: event.target.value })}><option value="">All trips</option><option value="false">One way</option><option value="true">Round trip</option></select></FilterField></div>
      <FilterField label="Client"><select className={styles.select} value={filters.clientId} onChange={(event) => patchFilters({ clientId: event.target.value, projectId: "" })}><option value="">All clients</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></FilterField><FilterField label="Project"><select className={styles.select} value={filters.projectId} onChange={(event) => patchFilters({ projectId: event.target.value })}><option value="">All projects</option>{activeProjects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></FilterField>
      <FilterField label="Billable"><select className={styles.select} value={filters.billable} onChange={(event) => patchFilters({ billable: event.target.value })}><option value="">Any</option><option value="true">Yes</option><option value="false">No</option></select></FilterField><FilterField label="Purpose"><input className={styles.input} list="mileage-purposes" value={filters.purpose} onChange={(event) => patchFilters({ purpose: event.target.value })} /><datalist id="mileage-purposes">{facets.purposes.map((item) => <option key={item.value} value={item.value} />)}</datalist></FilterField>
      <FilterField label="Trip name"><input className={styles.input} value={filters.tripName} onChange={(event) => patchFilters({ tripName: event.target.value })} /></FilterField><FilterField label="Start address"><input className={styles.input} value={filters.startAddress} onChange={(event) => patchFilters({ startAddress: event.target.value })} /></FilterField><FilterField label="End address"><input className={styles.input} value={filters.endAddress} onChange={(event) => patchFilters({ endAddress: event.target.value })} /></FilterField><FilterField label="Notes"><input className={styles.input} value={filters.notes} onChange={(event) => patchFilters({ notes: event.target.value })} /></FilterField>
      <FilterField label="Min one-way miles"><input className={styles.input} type="number" min="0" value={filters.milesMin} onChange={(event) => patchFilters({ milesMin: event.target.value })} /></FilterField><FilterField label="Max one-way miles"><input className={styles.input} type="number" min="0" value={filters.milesMax} onChange={(event) => patchFilters({ milesMax: event.target.value })} /></FilterField><FilterField label="Min total miles"><input className={styles.input} type="number" min="0" value={filters.totalMilesMin} onChange={(event) => patchFilters({ totalMilesMin: event.target.value })} /></FilterField><FilterField label="Max total miles"><input className={styles.input} type="number" min="0" value={filters.totalMilesMax} onChange={(event) => patchFilters({ totalMilesMax: event.target.value })} /></FilterField>
      <FilterField label="Min reimbursement"><input className={styles.input} type="number" min="0" value={filters.reimbursementMin} onChange={(event) => patchFilters({ reimbursementMin: event.target.value })} /></FilterField><FilterField label="Max reimbursement"><input className={styles.input} type="number" min="0" value={filters.reimbursementMax} onChange={(event) => patchFilters({ reimbursementMax: event.target.value })} /></FilterField><FilterField label="Entry ID"><input className={styles.input} value={filters.id} onChange={(event) => patchFilters({ id: event.target.value })} /></FilterField><FilterField label="Imported ID"><input className={styles.input} value={filters.mcId} onChange={(event) => patchFilters({ mcId: event.target.value })} /></FilterField>
      <FilterField label="Created from"><input className={styles.input} type="date" value={filters.createdFrom} onChange={(event) => patchFilters({ createdFrom: event.target.value })} /></FilterField><FilterField label="Created to"><input className={styles.input} type="date" value={filters.createdTo} onChange={(event) => patchFilters({ createdTo: event.target.value })} /></FilterField><FilterField label="Updated from"><input className={styles.input} type="date" value={filters.updatedFrom} onChange={(event) => patchFilters({ updatedFrom: event.target.value })} /></FilterField><FilterField label="Updated to"><input className={styles.input} type="date" value={filters.updatedTo} onChange={(event) => patchFilters({ updatedTo: event.target.value })} /></FilterField>
    </>}>
      <FilterField label="Search"><div style={{ position: "relative" }}><Search size={15} style={{ position: "absolute", left: 11, top: 13, color: "var(--muted)" }} /><input className={styles.input} style={{ paddingLeft: 34 }} placeholder="Search mileage" value={filters.search} onChange={(event) => patchFilters({ search: event.target.value })} /></div></FilterField><FilterField label="From"><input className={styles.input} type="date" value={filters.from} onChange={(event) => patchFilters({ from: event.target.value })} /></FilterField><FilterField label="To"><input className={styles.input} type="date" value={filters.to} onChange={(event) => patchFilters({ to: event.target.value })} /></FilterField><FilterField label="Trip type"><select className={styles.select} value={filters.roundTrip} onChange={(event) => patchFilters({ roundTrip: event.target.value })}><option value="">All trips</option><option value="false">One way</option><option value="true">Round trip</option></select></FilterField>
    </FilterBar>
    <section className={styles.ledgerSurface} aria-busy={loading}>{loading ? <div className={styles.loadingBar} /> : null}{entries.length === 0 && !loading ? <div className={styles.emptyState}><div><MapPin size={26} /><h2>{hasAnyRecords ? "No mileage trips yet" : "No trips match these filters"}</h2><p>{hasAnyRecords ? "Log the first business trip to start the ledger." : "Clear one or more filters to broaden the result set."}</p>{activeFilters.length ? <button type="button" className={styles.secondaryButton} onClick={() => setFilters((current) => ({ ...DEFAULT_FILTERS, pageSize: current.pageSize }))}>Clear filters</button> : <button type="button" className={styles.primaryButton} onClick={() => openCreate()}><Plus size={15} /> Log trip</button>}</div></div> : <DataTable rows={entries} columns={columns} rowKey={(entry) => entry.id} sort={filters.sort} direction={filters.direction} onSort={(sort) => patchFilters({ sort: sort as MileageSort, direction: filters.sort === sort && filters.direction === "desc" ? "asc" : "desc" })} renderMobile={(entry) => <article className={styles.mobileRow}><div className={styles.mobileRowHead}><div className={styles.mobileRowTitle}>{entry.tripName || entry.purpose || "Untitled trip"}</div><div className={styles.rowActions}><button type="button" className={styles.iconButton} onClick={() => openEdit(entry)} aria-label="Edit trip"><Pencil size={15} /></button><button type="button" className={styles.iconButton} onClick={() => setDeleteEntry(entry)} aria-label="Delete trip"><Trash2 size={15} /></button></div></div><p className={styles.mobileRowDetails}>{entry.startAddress || "Start"} → {entry.endAddress || "Destination"}</p><div className={styles.mobileRowMeta}><span>{friendlyDate(entry.date)}</span><span>{entry.totalMiles.toFixed(2)} mi</span><span>{money(entry.totalMiles * rate)}</span><span>{entry.roundTrip ? "Round trip" : "One way"}</span></div></article>} />}
      <footer className={styles.ledgerFooter}><div className={styles.footerTotals}><span className={styles.footerTotal}><strong>{totals.entries}</strong><span>trips</span></span><span className={styles.footerTotal}><strong>{totals.totalMiles.toFixed(1)}</strong><span>miles</span></span><span className={styles.footerTotal}><strong>{money(totals.reimbursement)}</strong><span>reimbursement</span></span></div><div className={styles.pagination}><select className={`${styles.select} ${styles.pageSize}`} aria-label="Rows per page" value={filters.pageSize} onChange={(event) => patchFilters({ pageSize: Number(event.target.value) })}><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select><span className={styles.pageStatus}>Page {pageInfo.totalPages === 0 ? 0 : pageInfo.page} of {pageInfo.totalPages}</span><button type="button" className={styles.pageButton} disabled={!pageInfo.hasPreviousPage || loading} onClick={() => patchFilters({ page: filters.page - 1 }, true)}>Previous</button><button type="button" className={styles.pageButton} disabled={!pageInfo.hasNextPage || loading} onClick={() => patchFilters({ page: filters.page + 1 }, true)}>Next</button></div></footer>
    </section>
    <RecordSheet open={sheetMode !== null} title={sheetMode === "edit" ? "Edit trip" : "Log trip"} subtitle={sheetMode === "create" && recent.length ? "Choose a recent route or enter a new trip" : undefined} dirty={formDirty} onClose={() => setSheetMode(null)} footer={<>{sheetMode === "create" ? <button type="submit" form={formId} name="intent" value="another" className={styles.secondaryButton} disabled={busy}>Save & add another</button> : null}<button type="submit" form={formId} name="intent" value="close" className={styles.primaryButton} disabled={busy}>{busy ? "Saving…" : sheetMode === "edit" ? "Save changes" : "Save trip"}</button></>}>
      {formSeed ? <MileageForm key={formKey} formId={formId} initial={formSeed} clients={clients} projects={projects} recent={recent} rate={rate} mapsConfigured={mapsConfigured} onDirtyChange={setFormDirty} onSubmit={async (values, addAnother) => { const success = await mutate(editingEntry ? "PUT" : "POST", editingEntry ? `/api/mileage/${editingEntry.id}` : "/api/mileage", payload(values)); if (!success) return; setFormDirty(false); if (addAnother) { setFormSeed({ ...values, tripName: "", purpose: "", notes: "" }); setFormKey((current) => current + 1); } else setSheetMode(null); }} /> : null}
    </RecordSheet>
    <DeleteDialog open={Boolean(deleteEntry)} title="Delete trip?" description={deleteEntry ? `${friendlyDate(deleteEntry.date)} · ${deleteEntry.tripName || deleteEntry.purpose || `${deleteEntry.totalMiles.toFixed(2)} miles`}. This cannot be undone.` : ""} confirmLabel="Delete trip" busy={busy} onCancel={() => setDeleteEntry(null)} onConfirm={() => { if (!deleteEntry) return; void mutate("DELETE", `/api/mileage/${deleteEntry.id}`).then((success) => { if (success) setDeleteEntry(null); }); }} />
  </TransactionPage>;
}
